plainbox:runner: Always return a number as return_code
As _just_run_command() expects integers and fails if return_code is None:

_just_run_command
    elif return_code < 0:
TypeError: unorderable types: NoneType() < int()