plainbox:secure:job: remove unused modify_execution_environment
The BaseJob.modify_execution_environment() used to be a part of the
code that computed environment for executing jobs. This is now performed
by execution controllers and job definitions no longer know anything about
it.

This particular piece of code was found to fail by the meta-test test
provider.

ERROR: test_checkbox_env (impl.secure.test_job.JobEnvTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/zyga/checkbox/plainbox/plainbox/impl/secure/test_job.py", line 124, in test_checkbox_env
    env = self.job.modify_execution_environment(base_env, [path])
  File "/home/zyga/checkbox/plainbox/plainbox/impl/secure/job.py", line 134, in modify_execution_environment
    env['CHECKBOX_DATA'] = environ['CHECKBOX_DATA']
KeyError: 'CHECKBOX_DATA'

Signed-off-by: Zygmunt Krynicki <zygmunt.krynicki@canonical.com>